CREATE TABLE CUSTOMER(
  CUSTOMER_ID INT PRIMARY KEY NOT NULL
  GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
  CUSTOMER_NAME CHAR(30),
  CUSTOMER_ADDRESS CHAR(30),
  START_DATE DATE,
  DUE_DATE DATE);
